#!/bin/sh

url="https://git.kernel.org/pub/scm/git/git.git/plain/contrib/completion"
url="https://git.kernel.org/pub/scm/git/git.git/plain/contrib/completion"
version="$(git --version | awk '{print $3}')"

curl -s -o git-completion.zsh "${url}/git-completion.zsh" &&
curl -s -o git-completion.bash "${url}/git-completion.bash" &&
curl -s -o git-prompt.sh "${url}/git-prompt.sh"
